create database first_security;

create table persons
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(100) NOT NULL,
    year_of_birth INTEGER      NOT NULL,
    password      varchar      NOT NULL
);

INSERT INTO persons (username, year_of_birth, password)
VALUES ('user_1', 1991, 'password_user1'),
    ('user_2', 1996, 'password_user2'),
    ('user_3', 1996, 'password_user3');
