create database first_security;

create table persons
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   varchar(100) NOT NULL,
    birth_date DATE         NOT NULL,
    password   varchar      NOT NULL
);

INSERT INTO persons (username, birth_date, password)
VALUES ('user_1', '1991-04-04', 'password_user1'),
       ('user_2', '1996-01-02', 'password_user2'),
       ('user_3', '2000-03-05', 'password_user3');

INSERT INTO persons (username, birth_date, password)
VALUES ('root', '1991-04-04', '12345');

drop table persons;